name: snakes_fight
description: "A real-time multiplayer Snake game built with Flutter and Firebase."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  
  # For settings persistence
  shared_preferences: ^2.2.2
  
  # For audio playback
  audioplayers: ^6.0.0
  
  # Firebase dependencies
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_database: ^11.1.4
  firebase_analytics: ^11.3.3
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^4.2.1
  
  # Google Sign-In
  google_sign_in: ^6.1.5
  
  # Code generation for data models
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0
  
  # Additional development tools
  very_good_analysis: ^5.1.0
  import_sorter: ^4.6.0
  
  # Testing dependencies
  mockito: ^5.4.4
  build_runner: ^2.4.7
  test: ^1.24.3
  network_image_mock: ^2.1.1
  
  # Code generation
  freezed: ^2.4.7
  json_serializable: ^6.7.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# Platform-specific configuration
flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/sounds/
    - assets/sounds/game/
    - assets/sounds/menu/

  # Fonts (can be added later for custom styling)
  # fonts:
  #   - family: GameFont
  #     fonts:
  #       - asset: fonts/GameFont-Regular.ttf
  #       - asset: fonts/GameFont-Bold.ttf
  #         weight: 700

# Platform configurations
platforms:
  android:
    package_name: com.snakesfight.game
    min_sdk_version: 21
    target_sdk_version: 34
    
  ios:
    bundle_id: com.snakesfight.game
    deployment_target: 12.0
    
  web:
    web_renderer: canvaskit
    base_href: /
