// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvbnWcnpMJUr0mF526fw3HLiqQ3UydfpI',
    appId: '1:664645409053:web:cbaca6ad62eceaecafe9f4',
    messagingSenderId: '664645409053',
    projectId: 'snakes-fight-dev',
    authDomain: 'snakes-fight-dev.firebaseapp.com',
    databaseURL: 'https://snakes-fight-dev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'snakes-fight-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpFRzaZXb7mHt9ajOlEIuenLUhGBFeF2g',
    appId: '1:664645409053:android:9d77a5a92ef64bb2afe9f4',
    messagingSenderId: '664645409053',
    projectId: 'snakes-fight-dev',
    databaseURL: 'https://snakes-fight-dev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'snakes-fight-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbChlt8G0ikaHWAalez5fy5Doh9pTIgr8',
    appId: '1:664645409053:ios:50143bf437aab8a5afe9f4',
    messagingSenderId: '664645409053',
    projectId: 'snakes-fight-dev',
    databaseURL: 'https://snakes-fight-dev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'snakes-fight-dev.firebasestorage.app',
    iosBundleId: 'com.example.snakesFight',
  );
}
